grails-app/domain/demo/Kommune.groovy
package demo

class Kommune {
    String nr
    String navn
    Integer areal
    String kontaktEmail
    String kontaktTelefon

    Region getRegion() {
        // Region.findByNr(regionsNr)
    }

    static transients = ['region']

    static constraints = {
        nr(nullable: false, unique: true)
        navn(nullable: false)
        areal(nullable: true)
        kontaktEmail(nullable: true, email: true)
        kontaktTelefon(nullable: true)
    }

    static mapping = {
        kontaktEmail column: 'email'
    }

    String toString() {
        "$nr: $navn ($areal)"
    }
}

grails-app/controllers/demo/KommuneController.groovy
package demo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['ROLE_USER'])
class KommuneController {
    def kommuneService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond kommuneService.getKommuner(params), model:[kommuneInstanceCount: kommuneService.count]
    }
//    Synthesized method of show(Kommune kommuneInstance)
//    def show() {
//        Long id = params.long('id')
//        return show(Kommune.get(id))
//    }


    @Secured(['ROLE_ADMIN'])
    def loadRegion(String region) {
        kommuneService.loadRegion(region)
        render('ok')
    }

    def show(Kommune kommuneInstance) {
        respond kommuneInstance
    }

    def create() {
        def kommune = new Kommune(params)
        respond kommune
    }

    @Transactional
    def save(Kommune kommuneInstance) {
        if (kommuneInstance == null) {
            notFound()
            return
        }

        if (kommuneInstance.hasErrors()) {
            respond kommuneInstance.errors, view:'create'
            return
        }

        kommuneInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'kommune.label', default: 'Kommune'), kommuneInstance.id])
                redirect kommuneInstance
            }
            rss {}
            '*' { respond kommuneInstance, [status: CREATED] }
        }
    }

    def edit(Kommune kommuneInstance) {
        respond kommuneInstance
    }

    @Transactional
    def update(Kommune kommuneInstance) {
        if (kommuneInstance == null) {
            notFound()
            return
        }

        if (kommuneInstance.hasErrors()) {
            respond kommuneInstance.errors, view:'edit'
            return
        }

        kommuneInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Kommune.label', default: 'Kommune'), kommuneInstance.id])
                redirect kommuneInstance
            }
            '*'{ respond kommuneInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Kommune kommuneInstance) {

        if (kommuneInstance == null) {
            notFound()
            return
        }

        kommuneInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Kommune.label', default: 'Kommune'), kommuneInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'kommune.label', default: 'Kommune'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/kommune/_form.gsp
<%@ page import="demo.Kommune" %>

<f:all bean="${kommuneInstance}"/>

grails-app/views/kommune/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'kommune.label', default: 'Kommune')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-kommune" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-kommune" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${kommuneInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${kommuneInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: kommuneInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/kommune/edit.gsp
<%@ page import="demo.Kommune" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'kommune.label', default: 'Kommune')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-kommune" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-kommune" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${kommuneInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${kommuneInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: kommuneInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${kommuneInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/kommune/index.gsp
<%@ page import="demo.Kommune" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'kommune.label', default: 'Kommune')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-kommune" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-kommune" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="nr" title="${message(code: 'kommune.nr.label', default: 'Nr')}"/>

            <g:sortableColumn property="navn" title="${message(code: 'kommune.navn.label', default: 'Navn')}"/>

            <g:sortableColumn property="areal" title="${message(code: 'kommune.areal.label', default: 'Areal')}"/>

            <g:sortableColumn property="kontaktEmail" title="${message(code: 'kommune.kontaktEmail.label', default: 'Kontakt Email')}"/>

            <g:sortableColumn property="kontaktTelefon" title="${message(code: 'kommune.kontaktTelefon.label', default: 'Kontakt Telefon')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${kommuneInstanceList}" status="i" var="kommuneInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show" id="${kommuneInstance.id}">${fieldValue(bean: kommuneInstance, field: "nr")}</g:link></td>

                <td>${fieldValue(bean: kommuneInstance, field: "navn")}</td>

                <td>${fieldValue(bean: kommuneInstance, field: "areal")}</td>

                <td>${fieldValue(bean: kommuneInstance, field: "kontaktEmail")}</td>

                <td>${fieldValue(bean: kommuneInstance, field: "kontaktTelefon")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${kommuneInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/kommune/show.gsp
<%@ page import="demo.Kommune" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'kommune.label', default: 'Kommune')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-kommune" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-kommune" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list kommune">

        <g:if test="${kommuneInstance?.nr}">
            <li class="fieldcontain">
                <span id="nr-label" class="property-label"><g:message code="kommune.nr.label" default="Nr"/></span>

                <span class="property-value" aria-labelledby="nr-label"><g:fieldValue bean="${kommuneInstance}" field="nr"/></span>

            </li>
        </g:if>

        <g:if test="${kommuneInstance?.navn}">
            <li class="fieldcontain">
                <span id="navn-label" class="property-label"><g:message code="kommune.navn.label" default="Navn"/></span>

                <span class="property-value" aria-labelledby="navn-label"><g:fieldValue bean="${kommuneInstance}" field="navn"/></span>

            </li>
        </g:if>

        <g:if test="${kommuneInstance?.areal}">
            <li class="fieldcontain">
                <span id="areal-label" class="property-label"><g:message code="kommune.areal.label" default="Areal"/></span>

                <span class="property-value" aria-labelledby="areal-label"><g:fieldValue bean="${kommuneInstance}" field="areal"/></span>

            </li>
        </g:if>

        <g:if test="${kommuneInstance?.kontaktEmail}">
            <li class="fieldcontain">
                <span id="kontaktEmail-label" class="property-label"><g:message code="kommune.kontaktEmail.label" default="Kontakt Email"/></span>

                <span class="property-value" aria-labelledby="kontaktEmail-label"><g:fieldValue bean="${kommuneInstance}" field="kontaktEmail"/></span>

            </li>
        </g:if>

        <g:if test="${kommuneInstance?.kontaktTelefon}">
            <li class="fieldcontain">
                <span id="kontaktTelefon-label" class="property-label"><g:message code="kommune.kontaktTelefon.label" default="Kontakt Telefon"/></span>

                <span class="property-value" aria-labelledby="kontaktTelefon-label"><g:fieldValue bean="${kommuneInstance}" field="kontaktTelefon"/></span>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: kommuneInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${kommuneInstance}"><g:message code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>